version: '3'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    container_name: db_mysql

  phpweb:
    image: tommylau/php-5.2
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - mysql
    links:
    - mysql:mysql
    container_name: phpweb

  nginx:
    tty: true
    image: tommylau/nginx
    # restart: always #サーバ起動時コンテナ自動起動
    volumes:
      - ./src/:/var/www/html # phpweb と volumes を合わせる必要がある
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "9000:80"
    environment:
      - ROOT=/var/www/html
    depends_on:
      - mysql
      - phpweb
    links:
    - phpweb:phpweb
    container_name: nginx
    command: /bin/sh -c "envsubst '$$ROOT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"